#ifndef MPC_GFLAGS_H
#define MPC_GFLAGS_H
#include "gflags/gflags.h"
DECLARE_double(CET_COST_COEFFICIENT);
DECLARE_double(EPSI_COST_COEFFICIENT);
DECLARE_double(V_COST_COEFFICIENT);
DECLARE_double(DELTA_COST_COEFFICIENT);
DECLARE_double(DELTA_DIFF_COST_COEFFICIENT);
DECLARE_double(A_COST_COEFFICIENT);
DECLARE_double(A_DIFF_COST_COEFFICIENT);

DEFINE_double(CET_COST_COEFFICIENT, 1500, "CET COST Coefficient");
DEFINE_double(EPSI_COST_COEFFICIENT, 500, "");
DEFINE_double(V_COST_COEFFICIENT, 100, "");
DEFINE_double(DELTA_COST_COEFFICIENT, 10, "");
DEFINE_double(DELTA_DIFF_COST_COEFFICIENT, 10, "");
DEFINE_double(A_COST_COEFFICIENT, 20, "");
DEFINE_double(A_DIFF_COST_COEFFICIENT, 20, "");

#endif